/**
 * Aspose.Pdf RestApi
 * Aspose.Pdf RestApi provides a comprehensive set of endpoints for various PDF-related tasks, enabling efficient document processing and manipulation. Users can retrieve processing status, download files, manage file locks, parse documents, redact sensitive information, convert between formats, merge files, add watermarks, perform text searches, and much more. With endpoints for tasks like electronic signing, document comparison, and form filling, the API offers extensive functionality to cater to diverse PDF requirements.
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileProcessingErrorCode } from './fileProcessingErrorCode';
import { FileSafeResult } from './fileSafeResult';

/**
 * Response class to get or set any api call status
 */
export interface FileResponse { 
    /**
     * Get or set StatusCode
     */
    statusCode?: number;
    /**
     * Get or set Status
     */
    status?: string;
    /**
     * Get or set Text
     */
    text?: string;
    /**
     * Get or set Document locked with password
     */
    locked?: boolean;
    /**
     * Last updated
     */
    updated?: Date;
    /**
     * Get or set Files
     */
    sharedFiles?: Array<FileSafeResult>;
    /**
     * Get or set Files
     */
    files?: Array<string>;
    fileProcessingErrorCode?: FileProcessingErrorCode;
    /**
     * Get count of files
     */
    readonly fileCount?: number;
    /**
     * Get or set FileName
     */
    fileName?: string;
    /**
     * Get or set FolderName
     */
    folderName?: string;
    /**
     * Data displaying on file processing result page
     */
    resultData?: any;
    /**
     * Instance id where is processing located
     */
    appInstanceId?: string;
}