/**
 * Aspose.Pdf RestApi
 * Aspose.Pdf RestApi provides a comprehensive set of endpoints for various PDF-related tasks, enabling efficient document processing and manipulation. Users can retrieve processing status, download files, manage file locks, parse documents, redact sensitive information, convert between formats, merge files, add watermarks, perform text searches, and much more. With endpoints for tasks like electronic signing, document comparison, and form filling, the API offers extensive functionality to cater to diverse PDF requirements.
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type HashAlgorithm = 'SHA1' | 'SHA256' | 'SHA384' | 'SHA512' | 'MD5';

export const HashAlgorithm = {
    SHA1: 'SHA1' as HashAlgorithm,
    SHA256: 'SHA256' as HashAlgorithm,
    SHA384: 'SHA384' as HashAlgorithm,
    SHA512: 'SHA512' as HashAlgorithm,
    MD5: 'MD5' as HashAlgorithm
};