<?php
/**
 * ApiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.PDF for AWS
 *
 * Aspose.Pdf for AWS provides a comprehensive set of endpoints for various PDF-related tasks, enabling efficient document processing and manipulation. Users can retrieve processing status, download files, manage file locks, parse documents, redact sensitive information, convert between formats, merge files, add watermarks, perform text searches, and much more. With endpoints for tasks like electronic signing, document comparison, and form filling, the API offers extensive functionality to cater to diverse PDF requirements.
 *
 * OpenAPI spec version: v1
 * Contact: sales@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.60
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for pdfWebapiAddnumberPost
     *
     * Add Page Numbers to Document..
     *
     */
    public function testPdfWebapiAddnumberPostForm()
    {
    }

    /**
     * Test case for pdfWebapiChangeFontsPost
     *
     * Change Fonts in Provided Files..
     *
     */
    public function testPdfWebapiChangeFontsPostForm()
    {
    }

    /**
     * Test case for pdfWebapiComparisonPost
     *
     * Compare documents text..
     *
     */
    public function testPdfWebapiComparisonPostForm()
    {
    }

    /**
     * Test case for pdfWebapiCompressPost
     *
     * Compress Document..
     *
     */
    public function testPdfWebapiCompressPostForm()
    {
    }

    /**
     * Test case for pdfWebapiConvertPost
     *
     * Convert Document to Another Format..
     *
     */
    public function testPdfWebapiConvertPostForm()
    {
    }

    /**
     * Test case for pdfWebapiConvertWebpagePost
     *
     * Convert Web Page to Document..
     *
     */
    public function testPdfWebapiConvertWebpagePostForm()
    {
    }

    /**
     * Test case for pdfWebapiCropPost
     *
     * Crop Document..
     *
     */
    public function testPdfWebapiCropPostForm()
    {
    }

    /**
     * Test case for pdfWebapiDownloadIdGet
     *
     * File download..
     *
     */
    public function testPdfWebapiDownloadIdGet()
    {
    }

    /**
     * Test case for pdfWebapiEsignPost
     *
     * Sign Document with Certificate..
     *
     */
    public function testPdfWebapiEsignPostForm()
    {
    }

    /**
     * Test case for pdfWebapiExtractPost
     *
     * Extract Tables from Document..
     *
     */
    public function testPdfWebapiExtractPostForm()
    {
    }

    /**
     * Test case for pdfWebapiGifPost
     *
     * Make GIF..
     *
     */
    public function testPdfWebapiGifPostForm()
    {
    }

    /**
     * Test case for pdfWebapiHashPost
     *
     * Calculate Document Hash..
     *
     */
    public function testPdfWebapiHashPostForm()
    {
    }

    /**
     * Test case for pdfWebapiLockPost
     *
     * Lock document..
     *
     */
    public function testPdfWebapiLockPostForm()
    {
    }

    /**
     * Test case for pdfWebapiMergePost
     *
     * Merge Documents..
     *
     */
    public function testPdfWebapiMergePostForm()
    {
    }

    /**
     * Test case for pdfWebapiMetadataPost
     *
     * Read and Change Document Metadata..
     *
     */
    public function testPdfWebapiMetadataPostForm()
    {
    }

    /**
     * Test case for pdfWebapiOrganizePost
     *
     * Organize Document Pages..
     *
     */
    public function testPdfWebapiOrganizePostForm()
    {
    }

    /**
     * Test case for pdfWebapiParsePost
     *
     * Parse Document..
     *
     */
    public function testPdfWebapiParsePostForm()
    {
    }

    /**
     * Test case for pdfWebapiRedactPost
     *
     * Redact Document Text..
     *
     */
    public function testPdfWebapiRedactPostForm()
    {
    }

    /**
     * Test case for pdfWebapiRemoveIdPost
     *
     * Remove stored files..
     *
     */
    public function testPdfWebapiRemoveIdPost()
    {
    }

    /**
     * Test case for pdfWebapiRemovePost
     *
     * Remove Document Annotations..
     *
     */
    public function testPdfWebapiRemovePostForm()
    {
    }

    /**
     * Test case for pdfWebapiRemoveWatermarkPost
     *
     * Remove Document Watermark..
     *
     */
    public function testPdfWebapiRemoveWatermarkPostForm()
    {
    }

    /**
     * Test case for pdfWebapiRemovepagesPost
     *
     * Remove Pages from Document..
     *
     */
    public function testPdfWebapiRemovepagesPostForm()
    {
    }

    /**
     * Test case for pdfWebapiRepairPost
     *
     * Repair Document..
     *
     */
    public function testPdfWebapiRepairPostForm()
    {
    }

    /**
     * Test case for pdfWebapiResizePost
     *
     * Resize Document..
     *
     */
    public function testPdfWebapiResizePostForm()
    {
    }

    /**
     * Test case for pdfWebapiRotatePost
     *
     * Rotate Document..
     *
     */
    public function testPdfWebapiRotatePostForm()
    {
    }

    /**
     * Test case for pdfWebapiSearchPost
     *
     * Search Document Text..
     *
     */
    public function testPdfWebapiSearchPostForm()
    {
    }

    /**
     * Test case for pdfWebapiSearchablePost
     *
     * Make Scanned PDF Searchable..
     *
     */
    public function testPdfWebapiSearchablePostForm()
    {
    }

    /**
     * Test case for pdfWebapiSignaturePost
     *
     * Add Signature to Document..
     *
     */
    public function testPdfWebapiSignaturePostForm()
    {
    }

    /**
     * Test case for pdfWebapiSplitdocPost
     *
     * Split Document..
     *
     */
    public function testPdfWebapiSplitdocPostForm()
    {
    }

    /**
     * Test case for pdfWebapiSplitimagePost
     *
     * Split Image..
     *
     */
    public function testPdfWebapiSplitimagePostForm()
    {
    }

    /**
     * Test case for pdfWebapiStatusIdPost
     *
     * Processing status..
     *
     */
    public function testPdfWebapiStatusIdPost()
    {
    }

    /**
     * Test case for pdfWebapiUnlockPost
     *
     * Unlock Document..
     *
     */
    public function testPdfWebapiUnlockPostForm()
    {
    }

    /**
     * Test case for pdfWebapiVerifyEsignPost
     *
     * Verify Document Certificate..
     *
     */
    public function testPdfWebapiVerifyEsignPostForm()
    {
    }

    /**
     * Test case for pdfWebapiWatermarkPost
     *
     * Add Watermark to Document..
     *
     */
    public function testPdfWebapiWatermarkPostForm()
    {
    }

    /**
     * Test case for pdfWebapiWordcounterPost
     *
     * Count Words and Characters in Document..
     *
     */
    public function testPdfWebapiWordcounterPostForm()
    {
    }

    /**
     * Test case for pdfWebapiXfaconvertPost
     *
     * Convert XFA Format to Another Format..
     *
     */
    public function testPdfWebapiXfaconvertPostForm()
    {
    }
}
